# Generated by Django 2.2.6 on 2019-10-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marandmor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Price',
            field=models.IntegerField(default=200),
        ),
    ]
