# Generated by Django 2.2.6 on 2019-11-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marandmor', '0002_auto_20191006_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
