# Generated by Django 2.2.6 on 2019-11-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marandmor', '0003_auto_20191117_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Specification',
            field=models.TextField(default=''),
        ),
    ]
