# Generated by Django 2.2.6 on 2019-11-17 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marandmor', '0004_post_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Item',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modified_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marandmor.Post')),
            ],
        ),
    ]
