# Generated by Django 2.2.6 on 2020-01-06 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marandmor', '0005_auto_20191117_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Modified_By',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Modified_By', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='Modified_Date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Created_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Created_By', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Edit',
        ),
    ]
