# Generated by Django 2.2.6 on 2020-01-08 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marandmor', '0006_auto_20200106_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Modified_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Modified_By', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='Modified_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
